
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: D:\aliyun_workspace\java_zf
DB_NAME: java_zf
spring:
  datasource:
    url: jdbc:mysql://192.168.110.129:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

File:
  uploadPath: /root/